services:
  postgres:
    image: postgres:16-alpine
    container_name: flowise-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - flowise-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  flowise:
    image: flowiseai/flowise:latest # Using latest to ensure env vars are supported
    container_name: flowise
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Database configuration
      DATABASE_TYPE: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${POSTGRES_DB}
      
      # Base Path Configuration
      API_BASE_PATH: /flowise
      VITE_APP_BASE_PATH: /flowise

      # Authentication
      FLOWISE_USERNAME: ${FLOWISE_USERNAME}
      FLOWISE_PASSWORD: ${FLOWISE_PASSWORD}
      
      # Security
      FLOWISE_SECRETKEY_OVERWRITE: ${FLOWISE_SECRETKEY_OVERWRITE}
      
      # Server configuration
      PORT: 3000
      FLOWISE_FILE_SIZE_LIMIT: 50mb
    volumes:
      - flowise_data:/root/.flowise
    # The port is no longer exposed directly to the host. Nginx will handle access.
    # ports:
    #   - "3000:3000" 
    networks:
      - flowise-network
    command: ["sh", "-c", "sleep 3 && flowise start"]

  nginx:
    image: nginx:latest
    container_name: flowise-nginx
    restart: always
    ports:
      - "80:80"       # Or "443:443" for HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - flowise-network
    depends_on:
      - flowise

networks:
  flowise-network:
    driver: bridge

volumes:
  postgres_data:
  flowise_data:
